const assert=require('node:assert/strict');
const {createCombat}=require('../multiplayer-combat.cjs');
const players=new Map(['a','b'].map(id=>[id,{id,selectedCharacter:'soldier',movement:{x:250,y:1150,worldId:'main',onFoot:true}}]));
const combat=createCombat({spawnId:'loot',players},{now:0,random:()=>0});
const seq={a:0,b:0};
const act=(id,kind,time,extra={})=>combat.act(id,{kind,angle:0,spawnId:'loot',sequence:++seq[id],...extra},time);
combat.advance(0);
let item=combat.snapshot().pickups.find(p=>p.type==='enemyHelmet');
assert.ok(item.id.startsWith('loot:pickup:'));
assert.equal(act('a','collect',0,{pickupId:item.id}).ok,false,'Drop delay');
assert.equal(act('a','collect',301,{pickupId:item.id,armorValue:999}).ok,true);
assert.equal(act('b','collect',301,{pickupId:item.id}).ok,false,'Concurrent loser');
assert.equal(act('a','collect',302,{pickupId:item.id}).ok,false,'Duplicate claim');
assert.equal(combat.snapshot().players.find(p=>p.id==='a').equippedArmorValue,80,'Server item values');
assert.ok(!combat.snapshot().pickups.some(p=>p.id===item.id));
item=combat.snapshot().pickups.find(p=>p.type==='goldHelmet');
assert.equal(act('a','collect',303,{pickupId:item.id}).ok,false,'Too far');
players.get('a').movement={x:item.x,y:item.y,worldId:'village',onFoot:true};
assert.equal(act('a','collect',304,{pickupId:item.id}).ok,false,'Wrong world');
players.get('a').movement.worldId='main';
assert.equal(act('a','collect',305,{pickupId:item.id,spawnId:'stale'}).ok,false,'Wrong spawn');
assert.equal(act('a','collect',306,{pickupId:item.id}).ok,true);
assert.equal(combat.snapshot().players.find(p=>p.id==='a').backpack[0].type,'enemyHelmet');
assert.equal(act('a','equipHelmet',307,{index:0}).ok,true);
assert.equal(combat.snapshot().players.find(p=>p.id==='a').equippedArmorValue,80);
// Kill the actual server boss; its existing rare helmet must drop only once.
players.get('a').movement={x:900,y:700,worldId:'main',onFoot:true};
players.get('b').movement.worldId='village';
for(let i=0;i<16;i++) {act('a','fire',1000+i*100);combat.advance(1090+i*100);}
combat.advance(3000);
const rare=combat.snapshot().pickups.filter(p=>p.type==='rareHelmet');
assert.equal(rare.length,1);assert.equal(rare[0].armorValue,85);
players.get('a').movement={x:rare[0].x,y:rare[0].y,worldId:'main',onFoot:true};
assert.equal(act('a','collect',3001,{pickupId:rare[0].id}).ok,true);
combat.advance(6000);
assert.equal(combat.snapshot().pickups.filter(p=>p.type==='rareHelmet').length,0,'No repeated boss drop');
const ids=combat.snapshot().pickups.map(p=>p.id);
assert.equal(new Set(ids).size,ids.length);
console.log('Pickups: one-time claims, validation, authoritative equipment, backpack swaps and boss helmet drops passed');
