const fs = require('node:fs');
const assert = require('node:assert/strict');
const {ready, run} = require('./harness.cjs');
(async () => {
 await ready;
 run(`
 player.displayName = 'WaveTest'; selectCharacter('soldier');
 activateTutorialWorld();
 assert.ok(getVillagePortals().includes(WAVE_MODE_TILE));
 hero.x = WAVE_MODE_TILE.x - hero.radius + 1; hero.y = WAVE_MODE_TILE.y + 48;
 update(0.016);
 assert.equal(player.inWaveWorld, true, 'Touching tile edge enters wave map');
 assert.equal(player.inTutorialWorld, false);
 assert.equal(enemies.length, 0, 'Arrival has a preparation countdown');
 for (const entities of [trees, stones, buildings, units, pickups, tutorialNpcs, tutorialPlots, tutorialSites, tutorialRangeTargets, villagePaths, villageProps, forestEnemySpawners]) assert.equal(entities.length, 0);
 assert.equal(runtime.enemyHero.active, false);
 assert.equal(runtime.playerBase, null); assert.equal(runtime.enemyBase, null);
 assert.equal(getVillagePortals().length, 0); assert.equal(getHumveeTravelTiles().length, 0);
 hero.x = trader.x; hero.y = trader.y; assert.equal(isHeroNearTrader(), false);
 hero.x = villager.x; hero.y = villager.y; assert.equal(isHeroNearVillager(), false);
 hero.y = MAIN_LANE_Y; assert.equal(isHeroOnRoad(), false);
 hero.x = DEATH_ZONE.x + 30; hero.y = DEATH_ZONE.y + 30;
 update(0.016); assert.equal(hero.hp, hero.maxHp, 'No invisible main-world death zone');
 render();
 updateWaveMode(3);
 assert.equal(waveMode.wave, 1); assert.equal(enemies.length, 3);
 const beforeDistance = distance(enemies[0], hero);
 updateUnits(0.1, enemies, [hero], []);
 assert.ok(distance(enemies[0], hero) < beforeDistance, 'Wave enemies pursue the player');
 updateWaveMode(30); assert.equal(enemies.length, 3, 'Living enemies block the next wave');
 enemies.slice(1).forEach(enemy => enemy.hp = 0); cleanupDefeatedEnemies(); updateWaveMode(1);
 assert.equal(waveMode.wave, 1); assert.equal(enemies.length, 1);
 enemies[0].hp = 0; cleanupDefeatedEnemies(); updateWaveMode(0.016);
 assert.equal(waveMode.timer, 3);
 updateWaveMode(3); assert.equal(waveMode.wave, 2); assert.equal(enemies.length, 5);
 enemies.forEach(enemy => enemy.hp = 0); cleanupDefeatedEnemies(); updateWaveMode(0.016);
 assert.equal(waveMode.completed, true); assert.match(getWaveModeStatus(), /complete/);
 updateWaveMode(3); assert.equal(player.inTutorialWorld, true); assert.equal(player.inWaveWorld, false);
 assert.equal(enemies.length, 0, 'No third wave');
 activateWaveWorld(); updateWaveMode(3);
 hero.isDead = true; hero.hp = 0; updateWaveMode(10); assert.equal(waveMode.wave, 1);
 respawnHero(); assert.equal(player.inWaveWorld, true); assert.equal(hero.isDead, false);
 assert.equal(waveMode.wave, 0); assert.equal(enemies.length, 0); assert.equal(hero.x, WAVE_MODE.spawnX);
 updateWaveMode(3); assert.equal(enemies.length, 3);
 activateVillageWorld(); assert.equal(player.inWaveWorld, false); assert.equal(waveMode.wave, 0);
 activateWaveWorld(); travelToMainWorld(); assert.equal(player.inWaveWorld, false); render();
 `);
 console.log('Wave mode entry, empty map, pursuit, two-wave progression, completion, retry and travel tests passed.');
})().catch(error => {console.error(error); process.exitCode = 1;});
